perks = {
    "S": [{"id": "S0",
           "title": "Strength Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "S"},
          {"id": "S1",
           "title": "Iron Fist", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 18},
                     {"rank": 4, "level": 31},
                     {"rank": 5, "level": 46}]},
          {"id": "S2",
           "title": "Big Leagues", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 7},
                     {"rank": 3, "level": 15},
                     {"rank": 4, "level": 27},
                     {"rank": 5, "level": 42}]},
          {"id": "S3",
           "title": "Armorer", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 25},
                     {"rank": 4, "level": 39}]},
          {"id": "S4",
           "title": "Blacksmith", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 16},
                     {"rank": 3, "level": 29}]},
          {"id": "S5",
           "title": "Heavy Gunner", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 11},
                     {"rank": 3, "level": 21},
                     {"rank": 4, "level": 35},
                     {"rank": 5, "level": 47}]},
          {"id": "S6",
           "title": "Strong Back", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 10},
                     {"rank": 3, "level": 20},
                     {"rank": 4, "level": 30},
                     {"rank": 5, "level": 40}]},
          {"id": "S7",
           "title": "Steady Aim", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 28},
                     {"rank": 3, "level": 49}]},
          {"id": "S8",
           "title": "Basher", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 5},
                     {"rank": 3, "level": 14},
                     {"rank": 4, "level": 26}]},
          {"id": "S9",
           "title": "Rooted", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 22},
                     {"rank": 3, "level": 43}]},
          {"id": "S10",
           "title": "Pain Train", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 24},
                     {"rank": 3, "level": 50}]},
          {"id": "S11",
           "title": "Strength Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "S"}],
    "P": [{"id": "P0",
           "title": "Perception Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "P"},
          {"id": "P1",
           "title": "Pickpocket", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 6},
                     {"rank": 3, "level": 17},
                     {"rank": 4, "level": 30}]},
          {"id": "P2",
           "title": "Rifleman", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 18},
                     {"rank": 4, "level": 31},
                     {"rank": 5, "level": 46}]},
          {"id": "P3",
           "title": "Awareness", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 14}]},
          {"id": "P4",
           "title": "Locksmith", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 7},
                     {"rank": 3, "level": 18},
                     {"rank": 4, "level": 41}]},
          {"id": "P5",
           "title": "Demolition Expert", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 10},
                     {"rank": 3, "level": 22},
                     {"rank": 4, "level": 34}]},
          {"id": "P6",
           "title": "Night Person", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 25},
                     {"rank": 3, "level": 37}]},
          {"id": "P7",
           "title": "Refractor", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 11},
                     {"rank": 3, "level": 21},
                     {"rank": 4, "level": 35},
                     {"rank": 5, "level": 42}]},
          {"id": "P8",
           "title": "Sniper", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 26}]},
          {"id": "P9",
           "title": "Penetrator", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 28}]},
          {"id": "P10",
           "title": "Concentrated Fire", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 26},
                     {"rank": 3, "level": 50}]},
          {"id": "P11",
           "title": "Perception Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "P"}],    
    "E": [{"id": "E0",
           "title": "Endurance Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "E"},
          {"id": "E1",
           "title": "Toughness", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 18},
                     {"rank": 4, "level": 31},
                     {"rank": 5, "level": 46}]},
          {"id": "E2",
           "title": "Lead Belly", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 6},
                     {"rank": 3, "level": 17}]},
          {"id": "E3",
           "title": "Lifegiver", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 8},
                     {"rank": 3, "level": 20}]},
          {"id": "E4",
           "title": "Chem Resistant", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 22}]},
          {"id": "E5",
           "title": "Aquaboy/Aquagirl", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 21}]},
          {"id": "E6",
           "title": "Rad Resistant", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 26},
                     {"rank": 4, "level": 35}]},
          {"id": "E7",
           "title": "Adamantium Skeleton", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 26}]},
          {"id": "E8",
           "title": "Cannibal", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 19},
                     {"rank": 3, "level": 38}]},
          {"id": "E9",
           "title": "Ghoulish", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 24},
                     {"rank": 3, "level": 48},
                     {"rank": 4, "level": 50}]},
          {"id": "E10",
           "title": "Solar Powered", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 27},
                     {"rank": 3, "level": 50}]},
          {"id": "E11",
           "title": "Endurance Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "E"}],
    "C": [{"id": "C0",
           "title": "Charisma Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "C"},
          {"id": "C1",
           "title": "Cap Collector", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 20},
                     {"rank": 3, "level": 41}]},
          {"id": "C2",
           "title": "Lady Killer/Black Widow", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 7},
                     {"rank": 3, "level": 22}]},
          {"id": "C3",
           "title": "Lone Wanderer", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 17},
                     {"rank": 3, "level": 40},
                     {"rank": 4, "level": 50}]},
          {"id": "C4",
           "title": "Attack Dog", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 25},
                     {"rank": 4, "level": 31}]},
          {"id": "C5",
           "title": "Animal Friend", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 12},
                     {"rank": 3, "level": 28}]},
          {"id": "C6",
           "title": "Local Leader", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 14}]},
          {"id": "C7",
           "title": "Party Boy/Party Girl", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 15},
                     {"rank": 3, "level": 27}]},
          {"id": "C8",
           "title": "Inspirational", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 19},
                     {"rank": 3, "level": 42}]},
          {"id": "C9",
           "title": "Wasteland Whisperer", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 21},
                     {"rank": 3, "level": 49}]},
          {"id": "C10",
           "title": "Intimidation", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 23},
                     {"rank": 3, "level": 50}]},
          {"id": "C11",
           "title": "Charisma Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "C"}],
    "I": [{"id": "I0",
           "title": "Intelligence Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "I"},
          {"id": "I1",
           "title": "V.A.N.S.", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 36}]},
          {"id": "I2",
           "title": "Medic", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 18},
                     {"rank": 3, "level": 30},
                     {"rank": 4, "level": 49}]},
          {"id": "I3",
           "title": "Gun Nut", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 25},
                     {"rank": 4, "level": 39}]},
          {"id": "I4",
           "title": "Hacker", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 21},
                     {"rank": 4, "level": 33}]},
          {"id": "I5",
           "title": "Scrapper", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 23},
                     {"rank": 3, "level": 40}]},
          {"id": "I6",
           "title": "Science!", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 17},
                     {"rank": 3, "level": 28},
                     {"rank": 4, "level": 41}]},
          {"id": "I7",
           "title": "Chemist", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 16},
                     {"rank": 3, "level": 32},
                     {"rank": 4, "level": 45}]},
          {"id": "I8",
           "title": "Robotics Expert", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 19},
                     {"rank": 3, "level": 44}]},
          {"id": "I9",
           "title": "Nuclear Physicist", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 14},
                     {"rank": 3, "level": 26}]},
          {"id": "I10",
           "title": "Nerd Rage!", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 31},
                     {"rank": 3, "level": 50}]},
          {"id": "I11",
           "title": "Intelligence Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "I"}],
    "A": [{"id": "A0",
           "title": "Agility Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "A"},
          {"id": "A1",
           "title": "Gunslinger", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 7},
                     {"rank": 3, "level": 15},
                     {"rank": 4, "level": 27},
                     {"rank": 5, "level": 42}]},
          {"id": "A2",
           "title": "Commando", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 11},
                     {"rank": 3, "level": 21},
                     {"rank": 4, "level": 35},
                     {"rank": 5, "level": 49}]},
          {"id": "A3",
           "title": "Sneak", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 5},
                     {"rank": 3, "level": 12},
                     {"rank": 4, "level": 23},
                     {"rank": 5, "level": 38}]},
          {"id": "A4",
           "title": "Mister Sandman", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 17},
                     {"rank": 3, "level": 30}]},
          {"id": "A5",
           "title": "Action Boy/Action Girl", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 18},
                     {"rank": 3, "level": 38}]},
          {"id": "A6",
           "title": "Moving Target", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 24},
                     {"rank": 3, "level": 44}]},
          {"id": "A7",
           "title": "Ninja", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 16},
                     {"rank": 3, "level": 33}]},
          {"id": "A8",
           "title": "Quick Hands", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 28},
                     {"rank": 3, "level": 40}]},
          {"id": "A9",
           "title": "Blitz", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 29}]},
          {"id": "A10",
           "title": "Gun Fu", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 26},
                     {"rank": 3, "level": 50}]},
          {"id": "A11",
           "title": "Agility Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "A"}],
    "L": [{"id": "L0",
           "title": "Luck Leveling", 
           "ranks": [{"rank": 2, "level": 1},
                     {"rank": 3, "level": 1},
                     {"rank": 4, "level": 1},
                     {"rank": 5, "level": 1},
                     {"rank": 6, "level": 1},
                     {"rank": 7, "level": 1},
                     {"rank": 8, "level": 1},
                     {"rank": 9, "level": 1},
                     {"rank": 10, "level": 1}],
           "stat_up": "L"},
          {"id": "L1",
           "title": "Fortune Finder", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 5},
                     {"rank": 3, "level": 25},
                     {"rank": 4, "level": 40}]},
          {"id": "L2",
           "title": "Scrounger", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 7},
                     {"rank": 3, "level": 24},
                     {"rank": 4, "level": 37}]},
          {"id": "L3",
           "title": "Bloody Mess", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 9},
                     {"rank": 3, "level": 31},
                     {"rank": 4, "level": 47}]},
          {"id": "L4",
           "title": "Mysterious Stranger", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 22},
                     {"rank": 3, "level": 41},
                     {"rank": 4, "level": 49}]},
          {"id": "L5",
           "title": "Idiot Savant", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 11},
                     {"rank": 3, "level": 34}]},
          {"id": "L6",
           "title": "Better Criticals", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 15},
                     {"rank": 3, "level": 40}]},
          {"id": "L7",
           "title": "Critical Banker", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 17},
                     {"rank": 3, "level": 43},
                     {"rank": 4, "level": 50}]},
          {"id": "L8",
           "title": "Grim Reaper's Sprint", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 19},
                     {"rank": 3, "level": 46}]},
          {"id": "L9",
           "title": "Four Leaf Clover", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 13},
                     {"rank": 3, "level": 32},
                     {"rank": 4, "level": 48}]},
          {"id": "L10",
           "title": "Ricochet", 
           "ranks": [{"rank": 1, "level": 1},
                     {"rank": 2, "level": 29},
                     {"rank": 3, "level": 50}]},
          {"id": "L11",
           "title": "Luck Bobblehead", 
           "ranks": [{"rank": 1, "level": 1}],
           "free_stat_up": "L"}]
    }